---
version: 2
jobs:
  build:
    resource_class: small
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
            npm install
      - run:
          name: Run Tests
          command: |
            npm run lint
            npm run test

  deploy:
    resource_class: small
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
            npm install
      - run:
          name: Deploy
          command: |
            npm run publish
            .circle/tag_release.sh

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          context: org-global
      - deploy:
          context: org-global
          requires:
            - build
          filters:
            branches:
              only: master

experimental:
  notify:
    branches:
      only:
        - master
